import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { fetchBooks } from "../utilis/bookApi";

interface Book {
  id: number;
  title: string;
}

interface BookState {
  books: Book[];
  status: "idle" | "loading" | "succeeded" | "failed";
  error: string | null | undefined;
}

const initialState: BookState = {
  books: [],
  status: "idle",
  error: null,
};

// The function below is called a thunk and allows us to perform async logic.
export const fetchBooksAsync = createAsyncThunk(
  "books/fetchBooks",
  async () => {
    const response = await fetchBooks();
    return response.data;
  }
);

export const bookSlice = createSlice({
  name: "books",
  initialState,
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk.
  extraReducers: (builder) => {
    builder
      .addCase(fetchBooksAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(fetchBooksAsync.fulfilled, (state, action) => {
        state.status = "succeeded";
        state.books = action.payload;
      });
  },
});

export default bookSlice.reducer;
